### ISSUE TITLE
Installation in Raspberry pi

### ISSUE THREAD

**Issue by karan369** [divinity666/ruby-grafana-reporter#1]
Hi,

have a nice day !!!

How to install in raspberry pi..
Kindly provide the step by step instructions.

Looking forward to hearing from soon.

**Comment by divinity666** [comment]
Hi Karan

which raspberry image are you running?

Best regards

**Comment by karan369** [comment]
"Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"

**Comment by divinity666** [comment]
Should be a easy then:

  sudo apt-get install ruby
  gem install ruby-grafana-reporter

Then you should be ready to go.

**Comment by karan369** [comment]
Thanks.. I will try it.

**Comment by karan369** [comment]
Thanks.. I will try it.

In which location I need to create following file.
grafana-reporter.config

**Comment by divinity666** [comment]
Hi Karan,

1. Your choice. I propose to start by using the configuration wizard:
`ruby-grafana-reporter -w`
It will help you create a first configuration

2. This is only necessary, if the access rights to your grafana installation are
a) not unrestricted, i.e. you have to login first
b) the API key, you generate in grafana does not have ADMIN rights
In these case you can configure the datasources manually. The datasource ID can be found when editing your datasource in grafana, e.g. `http:/your-grafana-host/datasources/edit/1/`. In this case the `1` states the datasource ID. The name should also be taken from the grafana propery `name` at that place.

3. I am unsure what you are looking for. You may simply place multiple reports with different names in your `templates` folder. These can be called with the `var-template=<<your-template-name>>` parameter.
If you are rather looking for a way on how to render multiple reports at once, you'll have to place several calls with the different templates to the reporter service. Please note that each report is generated in a separate Thread, i.e. you don't have to wait for one report to finish before calling the service for another report.

Hope this helps

BTW: Thanks for your questions, I'll try to improve the install documentation for future with your comments :-)

**Comment by karan369** [comment]
Thanks for your supports.. I will test and get back to you.
