### ISSUE TITLE
Node exporter guide

### ISSUE THREAD

**Issue by DanSman** [divinity666/ruby-grafana-reporter#10]
Hey

I could need a little help with your reporter and I thought we could create a guide here for the Node Exporter Dashboard. Later you could move the guide to the wiki or something.

What do you think?

**Comment by divinity666** [comment]
Hi Dan,

first please describe your issue, then we can decide which way to go.

Waiting for your description of the issue.

Best regards
Christian

**Comment by DanSman** [comment]
Hey divinity666

I don't have a specific issue. I just don't know where to start. I just need the right direction :)

For example, an average monthly report of that (node exporter): 
![node](https://user-images.githubusercontent.com/28892085/130688825-d1ad4138-a729-4e86-aa8c-f4fba5ad3221.png)

So I have to add the following to `node_report.adoc`
grafana_default_dashboard: <dashboard_uid> # Where can I find the ID?
grafana_default_instance: <instance_name>  # Is it possible to use only what is currently selected in the "Hosts" section?
...

Best regards back ;)

**Comment by divinity666** [comment]
No further feedback since a while.

Feel free to reopen, if you are still missing something.
