### ISSUE TITLE
Customized report templates

### ISSUE THREAD

**Issue by DimitrovMiro** [divinity666/ruby-grafana-reporter#14]
**Describe the issue**
Is it possible to configure our own font in the report, like logo etc

**Comment by DimitrovMiro** [comment]
Hi,
do you have any idea why my custom template is not found. The debug log is saying

could not locate or load the pdf theme `basic-theme' in C:\Users\xxxx\Downloads\basic-theme.yml

**Comment by DimitrovMiro** [comment]
the call in the link section of Grafana

http://localhost:8815/render?var-template=miro_report&pdf-theme=basic-theme&pdf-themesdir=C:\Users\xxx\Downloads\basic-theme.yml

**Comment by divinity666** [comment]
Any updates? Otherwise I'll close the case because of missing information within the next days.

**Comment by DimitrovMiro** [comment]
that one is good, you can close it
