### ISSUE TITLE
Template variable replacement issue

### ISSUE THREAD

**Issue by DimitrovMiro** [divinity666/ruby-grafana-reporter#15]
**Describe the issue**
when having the following variables on the dashboard, the rendering fails with the following error

![image](https://user-images.githubusercontent.com/50617778/138867487-2396222a-7e96-4b9b-9885-e336a6bba511.png)

error in the report 
![image](https://user-images.githubusercontent.com/50617778/138867406-111b5754-caeb-43f8-8892-fce77298a7ee.png)

**Comment by divinity666** [comment]
One thing that comes to my mind here:

You are refering to ˋ$jobˋ in your first query. I guess, the reporter tries to replace this with your second variable names ˋjobˋ. Would that be the intended behvaiour?

**Comment by divinity666** [comment]
closing due to missing feedback
