### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by ECONOS** [divinity666/ruby-grafana-reporter#17]
Hi,

I have followed the instruction to download the .exe file.

After downloading it, I double click, an empty command prompt came out and disappered.

Open Powershell type: ruby-grafana-reporter -w
Open cmd type: ruby-grafana-reporter -w

Both came out:
'ruby-grafana-reporter' is not recognized as an internal or external command,
operable program or batch file.

Need advise on this. 
Or is there a video demonstrating on the installation process for windows?

**Comment by emanzx** [comment]
I would go with linux on windows. you can install WSL and install any linux variant, i recommend ubuntu and just apt-get install ruby then gem install ruby-grafana-reporter. 
notes on how to setup WSL https://docs.microsoft.com/en-us/windows/wsl/install
once you have any linux on windows, you can just run normally follow the linux guide.

**Comment by divinity666** [comment]
Hi ECONOS, this is a strange behavior. Are you sure that you tried calling the exe from the correct folder (maybe a stupid question...)?
Are you sure the exe file you downloaded is exactly named like that? Maybe your exe is simply named like e.g. 'ruby-grafana-reporter-0.5.0.exe' instead?

**Comment by divinity666** [comment]
closing due to missing feedback
