### ISSUE TITLE
How to use grafana variable in asciidoc 

### ISSUE THREAD

**Issue by emanzx** [divinity666/ruby-grafana-reporter#18]
**Describe the issue**
I want to display grafana variable value in asciidoc but could not find any reference in the documentations. eg. something that grafana-reporter by IzakMarais have in the default report template. Well would it possible to provide template like what IzakMarais do with his reporter. The current demo report template is too documented style which is not ready to use and need lots of learning for new user.

**Comment by divinity666** [comment]
Thanks for your feedback and honestly I guess you are right.

Do you have specific ideas for improvement?

**Comment by emanzx** [comment]
Show a value of a grafana variable in your dashboard? yes.. 
for now when im using grafana variable in my panel title the reporter only print "{}" and the inside is empty

**Comment by divinity666** [comment]
Would you maybe provide a more complete example, so that I can have a deeper look into this?

**Comment by divinity666** [comment]
Closing because of missing input
