### ISSUE TITLE
I am running the reporter on Linux, how to run it as a service/daemon so it does not stop when I sign out

### ISSUE THREAD

**Issue by DimitrovMiro** [divinity666/ruby-grafana-reporter#19]
**Describe the issue**
A clear and concise description of what the issue is. I am running the reporter on Linux Debian 9, how to run it as a service/daemon so it does not stop when I sign out
What was the expected behaviour?
I am starting it with ruby-grafana-exporter. When I close the session, it is stopped, grafana cannot call it. How to fix it

**Application call**
 - type of call [webservice or single-run]: 
 - call of reporter [e.g. ruby-grafana-reporter -c myconfig]: 
 - call of report creation, if running as webservice [e.g. http://localhost/render?var-template=test]: 

**Template file (if applicable)**
 - filename: 
 - relevant part of template file:
```
<<part of your template file goes here>>
```

**Configuration file**
 - created with configuration wizard version [e.g. 0.3.0 or MANUAL]: 
 - relevant part of configuration file (remember to X-out personal information as e.g. api_key):
```
<<part of your configuration file goes here>>
```

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Environment [e.g. source, gem, docker or windows-exe]: 
 - ruby Version, if source or gem environment [e.g. 2.3.7]: 
 - reporter Version [e.g. 0.3.0]:

**Comment by divinity666** [comment]
This has nothing to do with the reporter itself. Please google for apropriate documentation.

One starting point could be [here](https://www.howtogeek.com/687970/how-to-run-a-linux-program-at-startup-with-systemd/).
