### ISSUE TITLE
ruby-grafana-reporter does not listen to 127.0.0.1 and only listen at ::1 no other way to change to custom binding address

### ISSUE THREAD

**Issue by emanzx** [divinity666/ruby-grafana-reporter#27]
as I mentioned in the title, the web service only listen to ::1 at port we can configured.. but I could not configured the binding address. I am not sure if this is intended for security or something else. I also could not find any reference on the documentation.

**Comment by divinity666** [comment]
Currently it is only possible to configure the `webservice-port` in your configuration file. So listening to port 1, as you mentioned looks like this has been configured in your personal config file, correct?

Anyway: configuring another address is not possible. Could you maybe describe, what you would like to achieve? At first glance your requirement could be met by adding NGINX proxy in front of your server.

**Comment by emanzx** [comment]
Currently it is only possible to configure the webservice-port in your configuration file. So listening to port 1, as you mentioned looks like this has been configured in your personal config file, correct?
yes
Anyway: configuring another address is not possible. Could you maybe describe, what you would like to achieve? At first glance your requirement could be met by adding NGINX proxy in front of your server.
it would be easier just to change the binding address.. anyway.. I did try with nginx.. but encounter some error.. never mind.. I will look at it later..
