### ISSUE TITLE
Grafana_reporter.config examples

### ISSUE THREAD

**Issue by henjoe** [divinity666/ruby-grafana-reporter#30]
Hi I am trying to look at code files but I haven't seen any examples for grafana_report.config.
Would you mind share some example? 

Thanks and Regards,
Henjoe

**Comment by divinity666** [comment]
Hi Henjoe, there is no documentation for the configuration file as such. You may want to have a look in the `lib\grafana_reporter\configuration.rb`, which contains als evaluated keys including the logic (but again: not as a documentation).

Closest you may get is by creating a configuration file with the wizard (`-w` flag), which will generate a configuration file for you.

**Comment by divinity666** [comment]
Closing because of missing input
