### ISSUE TITLE
How to include panels as images or generate report for whole dashboard

### ISSUE THREAD

**Issue by aktentasche** [divinity666/ruby-grafana-reporter#32]
**Describe the issue**
Hi, this might be a bit of an unusual issue: I do not understand how to use the function calls in an .adoc.

I generated the demo_report and tried [to add an image](https://github.com/divinity666/ruby-grafana-reporter/blob/master/FUNCTION_CALLS.md#grafana_panel_image) from one of my panels like this:

```
= Demo report

Created by `+ruby-grafana-reporter+` version 0.6.2

:grafana_default_dashboard:AbCdEfGhI
grafana_panel_image:22
```

This only prints the above text into the PDF.  

Also, is there a way to just define a dashboard ID and generate a report for all panels in that dashboard? I think there is something that you have to add to a panel, a variable or something so that a panel is included. Are those the macros like PanelImageBlockMacro?

Thanks!

**Comment by divinity666** [comment]
Closely look in the demo report. I guess this is working?

You need to add the brackets behind your request:

`grafana_panel_image:22[]`

Currently there is no function available, which creates a whole dashboard as a report.

**Comment by divinity666** [comment]
Closing because of missing input
