### ISSUE TITLE
Grafana::DashboardDoesNotExistError

### ISSUE THREAD

**Issue by bhaumiksonii** [divinity666/ruby-grafana-reporter#37]
**Describe the issue**
i am running grafana dashboard on docker and than i ran the ruby-grafana-reporter with the template 
describing this 
````
= Demo report
Created by `+ruby-grafana-reporter+` version 0.6.2
:grafana_default_dashboard:lqDwALhVz[]
grafana_panel_image:2[]
````

but than i got this error  Grafana::DashboardDoesNotExistError i checked the json file it is the same as i described

**Comment by divinity666** [comment]
Please closely look at the wizard template file and the asciidoctor syntax. The brackets `[]` behind the `grafana_default_dashboard` are wrong.

Try again without it and it should proceed.

**Comment by divinity666** [comment]
Closing because of missing feedback
