### ISSUE TITLE
Header and footer document

### ISSUE THREAD

**Issue by fsa1803** [divinity666/ruby-grafana-reporter#4]
Hello.
I would like to insert some text in the header and at the footer of the pages. In the asciidoc documentation I see that we need to create an external theme file. Is it possible or is there another method?

Thanks

**Comment by divinity666** [comment]
To do so, you need to use the provided asciidoctor capabilities. So creating external theme files is the way to go. Here is a short description for applying PDF themes with the reporter:

* Create the external themes as described [here](#applying-your-theme)
* Specify [necessary variables](https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#applying-your-theme) (`pdf-theme`, `pdf-themesdir` and optionally `pdf-fontsdir`) in your configuration file in the `default-document-attributes` section, e.g.
```` 
default-document-attributes:
  pdf-theme: <<your_theme_name>>
  pdf-themesdir: <<path_to_your_themes>>
````
* Restart the report webservice, if applicable, or run the reporter command standalone from command line

If everything is setup properly, your style theme should be applied for the next renderings.

**Remark**: I guess it's not possible to specify these attributes as document attributes at the beginning of and `adoc` file. If that's the case (and if that is required), I could consider it as a parameter that can be specified for each rendering call to the reporter either by command line or by webservice call.

**Comment by fsa1803** [comment]
Thanks for your tips, everything works.
Attributes cannot be placed in the adoc file, but that's not a problem for me, I use an external theme. But I think that being able to insert the attributes in the adoc file is a nice evolution.

Thanks
