### ISSUE TITLE
[Question] Sample report format.

### ISSUE THREAD

**Issue by henjoe** [divinity666/ruby-grafana-reporter#40]
Hi @divinity666 , this is an awesome projects! and thank you for this. I actually new to this, and I am looking for an example on how I configure my own report? 

I was testing this tool using my self hosted grafana, I think it works fine as a web service since it outputs the report, here is my configuration on grafana as per documentation:

![image](https://user-images.githubusercontent.com/49782655/222938069-d645b709-425c-4d74-a022-8575fdfbefec.png)

When I click that link on my dashboard, it outputs this pdf file:
![image](https://user-images.githubusercontent.com/49782655/222938094-f9691b37-8f06-4323-abd8-ea9bf1961aba.png)

I believe this report template is the default template, but I wonder why didn't see any images in here? like my panels in a specific dashboards? What I actually want is to just print what is in my dashboard, see below:

![image](https://user-images.githubusercontent.com/49782655/222938127-1aee7da2-817b-4cf4-abd3-a83e200f8147.png)

When I click the "Print PDF Report", I was expecting that it automatically prints it in the pdf file, but again, in the report generated by the default template, it doesn't have any images. 

Now my question is how would I do that? If you can give me a documentation on what are the things I need to learn in order to achieve that would be very appreciated!

Thank you.

Regards,
Henjoe

**Comment by divinity666** [comment]
Hi Henjoe, thanks for trying out the reporter.

Well, unfortunately, it looks like the demo report is not working, as it does not show any data at all. I propose to run again the configuration wizard and see if the report afterwards contains data.

If not, we should investigate in the web URL of your dashboard from the browser and the generated template (*.adoc) file. If possible, it would be great to share those files. Maybe you can also provide the configuration file, but please x-out API keys and private data.

**Comment by henjoe** [comment]
Thanks @divinity666 ! I will try to do this and will get back to you. 

Regards,
Henjoe

**Comment by divinity666** [comment]
Closing because of missing feedback
