### ISSUE TITLE
send mail with report

### ISSUE THREAD

**Issue by hypePG** [divinity666/ruby-grafana-reporter#41]
hey,
thanks for the repo. this is probably a stupid question. but is there any chance this tool has the functionality to send created reports via smtp?
or would i need to expand the tool with the logic for this for example with the plugin interface you offer?

thanks in advance,
max

**Comment by divinity666** [comment]
No, there is no builtin functionality for that. Anyway you could e.g. use the reporter as a webservice, which is being called by NodeRed and in NodeRed you could then call SMTP.
Another way would be to call the reporter as a command line tool and use a command line script, e.g. bash, to do this automatized.

Hope this helps.

**Comment by divinity666** [comment]
Closing, because this functionality is no in focus for the reporter, because of potentially too many required features. Please refer to the provided approach.
