### ISSUE TITLE
Enhancement - render scale

### ISSUE THREAD

**Issue by ilmarietto123** [divinity666/ruby-grafana-reporter#44]
Hi Divinity666,
I found out it is not possible to set the rendering scale of a panel image if renderer is not a Grafana plugin but a standalone server (in my case, a container) using config files, both in Grafana and/or Grafana-image-renderer.
When a remote request appens, the value of "DeviceScaleFactor" is hardcoded overridden to 1.
The result is a poor quality image (low res).
I managed changing ruby-grafana-reporter.rb file, line 1174, like this and it works:

      "/render/d-solo/#{@dashboard.id}?scale=4&panelId=#{@model['id']}"

Maybe can be an idea to add a new parameter like "render-scale" for "grafana_panel_image" in a future release.
Thanks!

**Comment by divinity666** [comment]
Feature is now available in latest release.
