### ISSUE TITLE
Add SSL disable check

### ISSUE THREAD

**Issue by Petorus** [divinity666/ruby-grafana-reporter#48]
**Describe the issue**
SSL verification error when Grafana instance is in https with a self-signed certificate.
is it possible to add a '-sslCheck=false' option, as in the 'IzakMarais' project ?
I try with the option '--ssl-cert' but i have this error : 'C:/Users/xxxxxxxxxx/AppData/Local/Temp/ocrED8C.tmp/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect
 returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLEr
ror)'

**Application call**
 - type of call : webservice and single-run 

**Configuration file**
 - created with configuration wizard

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: 10
 - Grafana version [e.g. 6.3.4]: 9.0.5
 - Environment [e.g. source, gem, docker or windows-exe]: windows-exe
 - Ruby Version, if source or gem environment [e.g. 2.3.7]: 
 - Reporter version [e.g. 0.3.0]: v.0.6.6

Thanks for your help

**Comment by divinity666** [comment]
Thanks for your feedback. Makes sense. I will add it in a next release.

**Comment by bolausson** [comment]
I have a valid certificate (with wildcards for e.g. "*.test.lab" and Grafana is runngin on e.g. "grafana.test.lab" which internally resolves to 172.16.0.102.

I don't know much about ruby.
It looks like the connection is using the IP address to validate the SSL certificate against.
`SSL_connect returned=1 errno=0 peeraddr=172.16.0.102:3000 state=error: certificate verify failed (unable to get local issuer certificate)`

The SSL cert is only valid for the DNS name (e.g. grafana.test.lab) and not 172.16.0.102.

**Quick fix**
replace:
`@http.verify_mode = OpenSSL::SSL::VERIFY_PEER`
with:
`@http.verify_mode = OpenSSL::SSL::VERIFY_NONE`
in lib/grafana/webrequest.rb

https://github.com/divinity666/ruby-grafana-reporter/blob/9a4c385906c83aaadef4b9834ca2abab00262d68/lib/grafana/webrequest.rb#L62C7-L62C52

I would like to second the request for a "-sslCheck=fals" option.

Greetings,
Bjoern

**Comment by divinity666** [comment]
@bolausson did you configure the reporter to use the IP address or the DNS name? It should be working, if you use the DNS name there.

**Comment by bolausson** [comment]
When I did run the wizzard, I added the DNS name. I'll double check it.

**Comment by bolausson** [comment]
Yes, it already starts throwing errors during the wizzard phase (I replaced my original domain with "grafana.test.lab" in the below output:

```
/home/bolausson/.local/share/gem/ruby/3.0.0/bin/ruby-grafana-reporter -w
This wizard will guide you through an initial configuration for the ruby-grafana-reporter. The configuration file will be created in the current folder. Please make sure to specify necessary paths either with a relative or an absolute path properly.

Wizard is creating configuration file 'grafana_reporter.config'.

Specify port on which reporter shall run [8815]: 
Specify grafana host [http://localhost:3000]: https://grafana.test.lab:3000
Testing connection to 'https://grafana.test.lab:3000' _without_ API key...
SSL_connect returned=1 errno=0 peeraddr=172.16.0.102:3000 state=error: certificate verify failed (unable to get local issuer certificate)
done.
Grafana could not be accessed at 'https://grafana.test.lab:3000'. Do you want to use an [a]pi key, [r]e-enter url, or [i]gnore and proceed? [aRi]: a
Enter API key: glsa_XXXX
Testing connection to 'https://grafana.test.lab:3000' _with_ API key...
SSL_connect returned=1 errno=0 peeraddr=172.16.0.102:3000 state=error: certificate verify failed (unable to get local issuer certificate)
done.
Grafana could not be accessed at 'https://grafana.test.lab:3000'. Do you want to use an [a]pi key, [r]e-enter url, or [i]gnore and proceed? [aRi]: i
Specify path where templates shall be stored [./templates]:
```

**Comment by divinity666** [comment]
Version with new functionality is released. Please check it out and close the issue, if it fits your needs.

**Comment by bolausson** [comment]
How do I disable the SSL check?

--help doesn't show an option:

```
$ /home/bolausson/.local/share/gem/ruby/3.0.0/bin/ruby-grafana-reporter -v
0.8.0
$ /home/bolausson/.local/share/gem/ruby/3.0.0/bin/ruby-grafana-reporter --help
Usage: /usr/bin/ruby3.0 /home/bolausson/.local/share/gem/ruby/3.0.0/bin/ruby-grafana-reporter [options]
    -c, --config CONFIG_FILE_NAME    Specify custom configuration file, instead of grafana_reporter.config.
    -r, --register FILE              Register a custom plugin, e.g. your own Datasource implementation
    -d, --debug LEVEL                Specify detail level: FATAL, ERROR, WARN, INFO, DEBUG.
    -o, --output FILE                Output filename if only a single file is rendered
    -s, --set VARIABLE,VALUE         Set a variable value, which will be passed to the rendering
        --test GRAFANA_INSTANCE      test current configuration against given GRAFANA_INSTANCE
    -t, --template TEMPLATE          Render a single ASCIIDOC template to PDF and exit
    -w, --wizard                     Configuration wizard to prepare environment for the reporter.
    -v, --version                    Version information
    -h, --help                       Show this message
```

**Comment by bolausson** [comment]
I see - you have to add "**ssl-disable-verify: true**" to the configuration file - there is no command line flag:

```
grafana:
  default:
    host: https://grafana.test.lab:3000
    api_key: XyZ
    ssl-disable-verify: true
```

**Comment by divinity666** [comment]
Perfect, thanks for your feedback. @Petorus, feel free to reopen the case, if you still experience problems.
