### ISSUE TITLE
If this tool fits with reports to messanger (slack, teams etc)

### ISSUE THREAD

**Issue by andrejshapal** [divinity666/ruby-grafana-reporter#53]
My usecase is not only to send pdf reports, but also reports in slack messages (difference between alerts - alerts expressions are executed regulary, reports should be executed in specific time of the day, which is not possible to succeed with standard alerting tools (actually possible, but this is wrong approach). I found this reporting tool pretty fine. As far as I understand, I can generate with ERB anything I want, then pass it into cronjob and send to slack via webhook.

- What do you think about this? If you think this reporting tool is suitable for such task?
- Is it possible in current implementation to create panel screenshots with erb?
- Is this possible to mix erb and Asciidoctor in current implementation?

**Comment by divinity666** [comment]
Going through your questions:

- Yes, with ERB, you can do literally everything, that you can do with Ruby.
- You can call the reporter with a cronjob, have a webhook configured, that will call e.g. a local NodeRed endpoint and from that you could create a proper call to Slack, which can then create the desired post. This is possible and would mean a regular setup for me.
- It is not possible to mix Asciidoctor and ERB in one template.
- You can create panel a screenshots with ERB by using the `PanelImageQuery`. This will then return a PNG image, that can be embedded in your ERB for example.

Anyway, I have a strong feeling, that ERB might not be the best choice for your use-case. Did you already consider using the HTML export? Maybe it would be easier for you, to use that export format? You try it with parameter `--s convert-backend,html5`.

Hope this helps.

**Comment by andrejshapal** [comment]
Yep,
I have reviewed html format. I don't feel it is good idea to convert html into json for slack.
I will go deeper in erb to understand if it fits our needs.
